import {
  FarmerProfile,
  BuyerProfile,
  ProduceListing,
  Order,
  BulkQuoteRequest,
  NotificationItem,
  MandiRateTickerItem,
} from '../types';

export const MOCK_FARMER: FarmerProfile = {
  id: 'farmer_ramesh_1',
  name: 'Ramesh Patil',
  phone: '+91 98220 45123',
  email: 'ramesh.patil@agromail.in',
  farmName: 'Patil Agro Fresh Farms',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
  location: {
    village: 'Niphad',
    mandiHub: 'Lasalgaon Mandi Hub',
    district: 'Nashik',
    state: 'Maharashtra',
    distanceKm: 28,
  },
  isVerified: true,
  kycStatus: 'verified',
  rating: 4.9,
  reviewCount: 112,
  completedOrders: 94,
  totalProduceListed: 14,
  memberSince: 'March 2023',
  landholdingAcres: 18.5,
  certifications: ['APMC Registered Seller', 'Organic Grade Verified', 'ONDC Agri-Network Certified'],
  bankDetails: {
    accountHolder: 'Ramesh Baliram Patil',
    bankName: 'State Bank of India (Nashik Agri Branch)',
    accountNumberMasked: '•••• •••• •••• 8842',
    ifscCode: 'SBIN0001423',
  },
};

export const MOCK_FARMER_SHINDE: FarmerProfile = {
  id: 'farmer_shinde_2',
  name: 'Anand Shinde',
  phone: '+91 94223 88190',
  email: 'shinde.farms@agromail.in',
  farmName: 'Shinde Organic Orchards',
  avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
  location: {
    village: 'Pimpalgaon',
    mandiHub: 'Nashik APMC',
    district: 'Nashik',
    state: 'Maharashtra',
    distanceKm: 42,
  },
  isVerified: true,
  kycStatus: 'verified',
  rating: 4.8,
  reviewCount: 78,
  completedOrders: 65,
  totalProduceListed: 8,
  memberSince: 'June 2023',
  landholdingAcres: 24.0,
  certifications: ['GlobalGAP Compliant', 'APMC Registered Seller'],
  bankDetails: {
    accountHolder: 'Anand V. Shinde',
    bankName: 'Bank of Maharashtra',
    accountNumberMasked: '•••• •••• •••• 3190',
    ifscCode: 'MAHB0000412',
  },
};

export const MOCK_FARMER_DESHMUKH: FarmerProfile = {
  id: 'farmer_deshmukh_3',
  name: 'Sunita Deshmukh',
  phone: '+91 97654 11220',
  farmName: 'Deshmukh Golden Grain Farms',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
  location: {
    village: 'Walwa',
    mandiHub: 'Sangli Turmeric Mandi',
    district: 'Sangli',
    state: 'Maharashtra',
    distanceKm: 18,
  },
  isVerified: true,
  kycStatus: 'verified',
  rating: 4.95,
  reviewCount: 140,
  completedOrders: 128,
  totalProduceListed: 10,
  memberSince: 'January 2023',
  landholdingAcres: 32.0,
  certifications: ['GI-Tagged Sangli Turmeric Producer', 'FSSAI Certified', 'Export Quality Certified'],
  bankDetails: {
    accountHolder: 'Sunita R. Deshmukh',
    bankName: 'HDFC Bank (Sangli Main Branch)',
    accountNumberMasked: '•••• •••• •••• 5591',
    ifscCode: 'HDFC0000781',
  },
};

export const MOCK_BUYER: BuyerProfile = {
  id: 'buyer_mahafresh_1',
  name: 'Vikramaditya Rao',
  phone: '+91 98450 78210',
  email: 'procurement@mahafreshfoods.com',
  businessName: 'MahaFresh Wholesale Procurement Ltd',
  businessType: 'Wholesaler',
  gstin: '27AABCM8921R1Z8',
  isVerified: true,
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
  warehouses: [
    {
      id: 'wh_pune_central',
      label: 'Pune Central Cold Hub (Primary)',
      address: 'Plot 42, Sector 10, Bhosari MIDC',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411026',
      isPrimary: true,
    },
    {
      id: 'wh_mumbai_vashi',
      label: 'Navi Mumbai APMC Terminal',
      address: 'Warehouse Block C-14, Vashi Market Yard',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      pincode: '400703',
      isPrimary: false,
    },
  ],
  typicalMonthlyVolumeKg: 45000,
  completedProcurements: 142,
  memberSince: 'November 2022',
  preferredPaymentTerms: 'ONDC Escrow / RTGS 3-Day Settlement',
};

export const MOCK_PRODUCE_LISTINGS: ProduceListing[] = [
  {
    id: 'prod_tomato_hybrid_1',
    farmerId: MOCK_FARMER.id,
    farmer: MOCK_FARMER,
    name: 'Premium Hybrid Red Tomato (Abhinav)',
    category: 'vegetables',
    variety: 'Abhinav Hybrid F1',
    grade: 'Premium',
    qualityDescription: 'Firm red, 85-90mm uniform size, 14-day shelf life, zero pesticide residue report attached. Suitable for long-distance transport and retail chain packaging.',
    images: [
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1546470427-0d4db154ceb7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 3500,
    availableQuantity: 2200,
    reservedQuantity: 800,
    soldQuantity: 500,
    unit: 'kg',
    minOrderQuantity: 200,
    basePricePerUnit: 28,
    isNegotiable: true,
    priceTiers: [
      { minQty: 200, maxQty: 499, pricePerUnit: 30 },
      { minQty: 500, maxQty: 999, pricePerUnit: 28 },
      { minQty: 1000, pricePerUnit: 25 },
    ],
    harvestDate: '2026-08-11',
    availableFrom: '2026-08-12',
    availableUntil: '2026-08-20',
    location: {
      mandiHub: 'Lasalgaon Mandi Hub',
      district: 'Nashik',
      state: 'Maharashtra',
      distanceKm: 28,
    },
    status: 'active',
    createdAt: '2026-08-11T09:00:00Z',
    updatedAt: '2026-08-13T06:00:00Z',
    featured: true,
    tags: ['Fresh Harvest', 'Export Grade', 'Cold Storage Ready'],
  },
  {
    id: 'prod_onion_lasalgaon_2',
    farmerId: MOCK_FARMER.id,
    farmer: MOCK_FARMER,
    name: 'Lasalgaon Grade A Red Onion (Garwa)',
    category: 'vegetables',
    variety: 'Garwa Red (Late Kharif)',
    grade: 'A',
    qualityDescription: 'Single-centered, 55mm+ diameter, cured under shade for 10 days with dry tight outer skin. Excellent 6-month storage durability.',
    images: [
      'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 8000,
    availableQuantity: 5200,
    reservedQuantity: 1500,
    soldQuantity: 1300,
    unit: 'kg',
    minOrderQuantity: 500,
    basePricePerUnit: 22,
    isNegotiable: true,
    priceTiers: [
      { minQty: 500, maxQty: 999, pricePerUnit: 23 },
      { minQty: 1000, maxQty: 2999, pricePerUnit: 21 },
      { minQty: 3000, pricePerUnit: 19.5 },
    ],
    harvestDate: '2026-08-08',
    availableFrom: '2026-08-10',
    availableUntil: '2026-08-30',
    location: {
      mandiHub: 'Lasalgaon Mandi Hub',
      district: 'Nashik',
      state: 'Maharashtra',
      distanceKm: 28,
    },
    status: 'active',
    createdAt: '2026-08-08T10:30:00Z',
    updatedAt: '2026-08-12T14:20:00Z',
    featured: true,
    tags: ['Direct from Lasalgaon', 'Low Moisture', 'Bulk Deal'],
  },
  {
    id: 'prod_turmeric_sangli_3',
    farmerId: MOCK_FARMER_DESHMUKH.id,
    farmer: MOCK_FARMER_DESHMUKH,
    name: 'GI-Tagged Sangli Rajapuri Turmeric (Curcumin 4.8%)',
    category: 'spices',
    variety: 'Rajapuri Bold Finger',
    grade: 'Premium',
    qualityDescription: 'Laboratory tested 4.82% active curcumin content. Double polished dry turmeric fingers. Zero artificial polishing or lead chromate.',
    images: [
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 4000,
    availableQuantity: 3100,
    reservedQuantity: 400,
    soldQuantity: 500,
    unit: 'kg',
    minOrderQuantity: 100,
    basePricePerUnit: 145,
    isNegotiable: false,
    priceTiers: [
      { minQty: 100, maxQty: 499, pricePerUnit: 150 },
      { minQty: 500, maxQty: 1499, pricePerUnit: 142 },
      { minQty: 1500, pricePerUnit: 135 },
    ],
    harvestDate: '2026-08-01',
    availableFrom: '2026-08-05',
    availableUntil: '2026-11-30',
    location: {
      mandiHub: 'Sangli Turmeric Mandi',
      district: 'Sangli',
      state: 'Maharashtra',
      distanceKm: 18,
    },
    status: 'active',
    createdAt: '2026-08-05T11:00:00Z',
    updatedAt: '2026-08-12T16:00:00Z',
    featured: true,
    tags: ['GI Tagged', 'High Curcumin', 'Pharma & Food Grade'],
  },
  {
    id: 'prod_pomegranate_shinde_4',
    farmerId: MOCK_FARMER_SHINDE.id,
    farmer: MOCK_FARMER_SHINDE,
    name: 'Bhagwa Export Pomegranate (250g+ Arils)',
    category: 'fruits',
    variety: 'Bhagwa (Super Sindhuri)',
    grade: 'Premium',
    qualityDescription: 'Deep ruby red arils, soft seeds, high brix sugar index (15.5+). Packed in ventilated corrugated boxes for bulk dispatch.',
    images: [
      'https://images.unsplash.com/photo-1541345023926-55d6e0853f4b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 2500,
    availableQuantity: 1800,
    reservedQuantity: 300,
    soldQuantity: 400,
    unit: 'kg',
    minOrderQuantity: 150,
    basePricePerUnit: 115,
    isNegotiable: true,
    priceTiers: [
      { minQty: 150, maxQty: 499, pricePerUnit: 120 },
      { minQty: 500, maxQty: 999, pricePerUnit: 112 },
      { minQty: 1000, pricePerUnit: 105 },
    ],
    harvestDate: '2026-08-10',
    availableFrom: '2026-08-11',
    availableUntil: '2026-08-25',
    location: {
      mandiHub: 'Nashik APMC',
      district: 'Nashik',
      state: 'Maharashtra',
      distanceKm: 42,
    },
    status: 'active',
    createdAt: '2026-08-10T12:00:00Z',
    updatedAt: '2026-08-13T05:30:00Z',
    featured: false,
    tags: ['Export Grade', 'High Brix', 'Crushed Ice Dispatch'],
  },
  {
    id: 'prod_wheat_sharbati_5',
    farmerId: MOCK_FARMER.id,
    farmer: MOCK_FARMER,
    name: 'MP Sharbati Golden Wheat (100% Machine Cleaned)',
    category: 'grains',
    variety: 'C-306 Traditional Sharbati',
    grade: 'A',
    qualityDescription: 'Lustrous golden grain, heavy test weight (81 kg/hl), gluten 11.8%. Machine cleaned and destoned.',
    images: [
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 12000,
    availableQuantity: 9500,
    reservedQuantity: 1500,
    soldQuantity: 1000,
    unit: 'kg',
    minOrderQuantity: 1000,
    basePricePerUnit: 36,
    isNegotiable: false,
    priceTiers: [
      { minQty: 1000, maxQty: 2999, pricePerUnit: 36 },
      { minQty: 3000, maxQty: 5999, pricePerUnit: 34.5 },
      { minQty: 6000, pricePerUnit: 33 },
    ],
    harvestDate: '2026-07-25',
    availableFrom: '2026-08-01',
    availableUntil: '2026-12-31',
    location: {
      mandiHub: 'Ahmednagar APMC',
      district: 'Ahmednagar',
      state: 'Maharashtra',
      distanceKm: 65,
    },
    status: 'active',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
    featured: false,
    tags: ['Premium Flour Grade', 'Machine Destoned', 'Bulk Bags'],
  },
  {
    id: 'prod_potato_pune_6',
    farmerId: MOCK_FARMER_SHINDE.id,
    farmer: MOCK_FARMER_SHINDE,
    name: 'Manchar Table & Processing Potato (Chipsona-1)',
    category: 'vegetables',
    variety: 'Chipsona-1 (Low Sugar)',
    grade: 'A',
    qualityDescription: 'Ideal for chips and french fries with dry matter >21.5% and reducing sugar <0.1%. Clean soil-free skins.',
    images: [
      'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 6000,
    availableQuantity: 4200,
    reservedQuantity: 1000,
    soldQuantity: 800,
    unit: 'kg',
    minOrderQuantity: 500,
    basePricePerUnit: 19,
    isNegotiable: true,
    priceTiers: [
      { minQty: 500, maxQty: 1999, pricePerUnit: 19 },
      { minQty: 2000, maxQty: 4999, pricePerUnit: 17.5 },
      { minQty: 5000, pricePerUnit: 16 },
    ],
    harvestDate: '2026-08-06',
    availableFrom: '2026-08-08',
    availableUntil: '2026-09-15',
    location: {
      mandiHub: 'Pune Gultekdi Market Yard',
      district: 'Pune',
      state: 'Maharashtra',
      distanceKm: 55,
    },
    status: 'active',
    createdAt: '2026-08-08T11:30:00Z',
    updatedAt: '2026-08-12T15:00:00Z',
    featured: false,
    tags: ['Processing Grade', 'Low Sugar', 'Cold Stored'],
  },
  {
    id: 'prod_nagpur_oranges_7',
    farmerId: MOCK_FARMER.id,
    farmer: MOCK_FARMER,
    name: 'Nagpur Organic Mandarin Oranges (Grade A Sweet)',
    category: 'fruits',
    variety: 'Nagpur Mandarin',
    grade: 'A',
    qualityDescription: 'Thin peel, rich juice yield (48%+), sweet-tangy balanced flavor profile. Graded and wax-coated for fresh retail display.',
    images: [
      'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 3000,
    availableQuantity: 0,
    reservedQuantity: 0,
    soldQuantity: 3000,
    unit: 'kg',
    minOrderQuantity: 300,
    basePricePerUnit: 48,
    isNegotiable: false,
    priceTiers: [
      { minQty: 300, pricePerUnit: 48 },
    ],
    harvestDate: '2026-07-28',
    availableFrom: '2026-07-30',
    availableUntil: '2026-08-10',
    location: {
      mandiHub: 'Nagpur Orange Mandi',
      district: 'Nagpur',
      state: 'Maharashtra',
      distanceKm: 140,
    },
    status: 'sold_out',
    createdAt: '2026-07-28T09:00:00Z',
    updatedAt: '2026-08-10T18:00:00Z',
    featured: false,
    tags: ['Sold Out', 'High Juice Yield'],
  },
  {
    id: 'prod_green_chilli_8',
    farmerId: MOCK_FARMER_DESHMUKH.id,
    farmer: MOCK_FARMER_DESHMUKH,
    name: 'G4 Spicy Green Chilli (High Pungency)',
    category: 'vegetables',
    variety: 'G4 Hybrid Green',
    grade: 'A',
    qualityDescription: 'Dark glossy green, 9-11cm length, SHU 45,000+ pungency. Freshly harvested in mesh bags.',
    images: [
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80',
    ],
    totalQuantity: 1800,
    availableQuantity: 1800,
    reservedQuantity: 0,
    soldQuantity: 0,
    unit: 'kg',
    minOrderQuantity: 100,
    basePricePerUnit: 42,
    isNegotiable: true,
    priceTiers: [
      { minQty: 100, maxQty: 499, pricePerUnit: 42 },
      { minQty: 500, pricePerUnit: 38 },
    ],
    harvestDate: '2026-08-12',
    availableFrom: '2026-08-13',
    availableUntil: '2026-08-22',
    location: {
      mandiHub: 'Sangli Turmeric Mandi',
      district: 'Sangli',
      state: 'Maharashtra',
      distanceKm: 18,
    },
    status: 'paused',
    createdAt: '2026-08-12T14:00:00Z',
    updatedAt: '2026-08-13T04:00:00Z',
    featured: false,
    tags: ['High Pungency', 'Fresh Plucked'],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_vm_98214',
    orderNumber: 'VM-2026-98214',
    createdAt: '2026-08-12T10:15:00Z',
    status: 'preparing',
    farmerId: MOCK_FARMER.id,
    farmerName: MOCK_FARMER.name,
    farmerPhone: MOCK_FARMER.phone,
    farmerLocation: 'Niphad, Nashik (Lasalgaon Mandi)',
    buyerId: MOCK_BUYER.id,
    buyerName: MOCK_BUYER.name,
    businessName: MOCK_BUYER.businessName,
    buyerGstin: MOCK_BUYER.gstin,
    deliveryWarehouse: {
      label: 'Pune Central Cold Hub',
      address: 'Plot 42, Sector 10, Bhosari MIDC',
      city: 'Pune',
      state: 'Maharashtra',
    },
    dispatchType: 'ondc_logistics',
    paymentMethod: 'ondc_escrow',
    paymentStatus: 'paid_escrow',
    items: [
      {
        listingId: 'prod_tomato_hybrid_1',
        produceName: 'Premium Hybrid Red Tomato (Abhinav)',
        variety: 'Abhinav Hybrid F1',
        grade: 'Premium',
        quantity: 800,
        unitPrice: 28,
        totalPrice: 22400,
        imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80',
      },
    ],
    produceSubtotal: 22400,
    logisticsFee: 2400,
    mandiCessPlatformFee: 336,
    gstAmount: 0, // Fresh agricultural produce 0% GST
    grandTotal: 25136,
    timeline: [
      {
        status: 'new',
        title: 'Order Placed & Escrow Funded',
        description: 'MahaFresh Wholesale locked ₹25,136 in ONDC Agri Escrow.',
        timestamp: '12 Aug 2026, 10:15 AM',
        completed: true,
        current: false,
      },
      {
        status: 'accepted',
        title: 'Farmer Confirmed Order',
        description: 'Ramesh Patil accepted batch allocation for 800 kg Tomato.',
        timestamp: '12 Aug 2026, 10:45 AM',
        completed: true,
        current: false,
      },
      {
        status: 'preparing',
        title: 'Grading & Plastic Crates Packing',
        description: 'Produce is being weighed, sorted and loaded in ventilated crates.',
        timestamp: '13 Aug 2026, 08:30 AM',
        completed: true,
        current: true,
      },
      {
        status: 'ready_for_pickup',
        title: 'Ready for Truck Pickup',
        description: 'Scheduled pickup window 02:00 PM – 04:00 PM.',
        timestamp: 'Expected 13 Aug 2026, 02:00 PM',
        completed: false,
        current: false,
      },
      {
        status: 'in_transit',
        title: 'In Transit to Pune Hub',
        description: 'ONDC Logistics Fleet (MH-15-EG-4910). Driver: Sachin Jadhav.',
        timestamp: 'Expected 13 Aug 2026, 09:00 PM',
        completed: false,
        current: false,
      },
      {
        status: 'delivered',
        title: 'Delivered & Quality Verified',
        description: 'Escrow will be released to farmer upon warehouse weight slip.',
        timestamp: 'Expected 14 Aug 2026, 07:00 AM',
        completed: false,
        current: false,
      },
    ],
    eWayBillNumber: 'EWB-260813-88912',
    truckVehicleNumber: 'MH-15-EG-4910',
    driverPhone: '+91 97650 99211',
  },
  {
    id: 'ord_vm_98190',
    orderNumber: 'VM-2026-98190',
    createdAt: '2026-08-10T14:30:00Z',
    status: 'delivered',
    farmerId: MOCK_FARMER.id,
    farmerName: MOCK_FARMER.name,
    farmerPhone: MOCK_FARMER.phone,
    farmerLocation: 'Niphad, Nashik',
    buyerId: MOCK_BUYER.id,
    buyerName: MOCK_BUYER.name,
    businessName: MOCK_BUYER.businessName,
    buyerGstin: MOCK_BUYER.gstin,
    deliveryWarehouse: {
      label: 'Navi Mumbai APMC Terminal',
      address: 'Warehouse Block C-14, Vashi Market Yard',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
    },
    dispatchType: 'ondc_logistics',
    paymentMethod: 'ondc_escrow',
    paymentStatus: 'released_to_farmer',
    items: [
      {
        listingId: 'prod_onion_lasalgaon_2',
        produceName: 'Lasalgaon Grade A Red Onion',
        variety: 'Garwa Red',
        grade: 'A',
        quantity: 1300,
        unitPrice: 21,
        totalPrice: 27300,
        imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=400&q=80',
      },
    ],
    produceSubtotal: 27300,
    logisticsFee: 3200,
    mandiCessPlatformFee: 409,
    gstAmount: 0,
    grandTotal: 30909,
    timeline: [
      {
        status: 'new',
        title: 'Order Placed',
        description: 'Order placed with 100% Escrow deposit.',
        timestamp: '10 Aug 2026, 02:30 PM',
        completed: true,
        current: false,
      },
      {
        status: 'accepted',
        title: 'Confirmed by Farmer',
        description: '1,300 kg reserved from Lasalgaon store.',
        timestamp: '10 Aug 2026, 03:10 PM',
        completed: true,
        current: false,
      },
      {
        status: 'ready_for_pickup',
        title: 'Dispatched via Mandi Freight',
        description: 'Loaded onto 14-ft Eicher truck (MH-04-AX-8911).',
        timestamp: '11 Aug 2026, 06:00 PM',
        completed: true,
        current: false,
      },
      {
        status: 'delivered',
        title: 'Delivered & Accepted',
        description: 'Warehouse quality inspection passed. ₹27,300 released to Ramesh Patil.',
        timestamp: '12 Aug 2026, 09:30 AM',
        completed: true,
        current: true,
      },
    ],
  },
  {
    id: 'ord_vm_98240',
    orderNumber: 'VM-2026-98240',
    createdAt: '2026-08-13T06:45:00Z',
    status: 'new',
    farmerId: MOCK_FARMER.id,
    farmerName: MOCK_FARMER.name,
    farmerPhone: MOCK_FARMER.phone,
    farmerLocation: 'Niphad, Nashik',
    buyerId: 'buyer_rel_fresh',
    buyerName: 'Priya Sharma',
    businessName: 'Apex Fresh Agro Retail Ltd',
    buyerGstin: '27AABCA7712E1Z3',
    deliveryWarehouse: {
      label: 'Mumbai Central Hub',
      address: 'Goregaon East Logistics Park',
      city: 'Mumbai',
      state: 'Maharashtra',
    },
    dispatchType: 'ondc_logistics',
    paymentMethod: 'ondc_escrow',
    paymentStatus: 'paid_escrow',
    items: [
      {
        listingId: 'prod_tomato_hybrid_1',
        produceName: 'Premium Hybrid Red Tomato (Abhinav)',
        variety: 'Abhinav Hybrid F1',
        grade: 'Premium',
        quantity: 500,
        unitPrice: 28,
        totalPrice: 14000,
        imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80',
      },
    ],
    produceSubtotal: 14000,
    logisticsFee: 1800,
    mandiCessPlatformFee: 210,
    gstAmount: 0,
    grandTotal: 16010,
    timeline: [
      {
        status: 'new',
        title: 'New Bulk Order Received',
        description: 'Awaiting farmer acceptance. Escrow payment verified.',
        timestamp: '13 Aug 2026, 06:45 AM',
        completed: true,
        current: true,
      },
    ],
  },
];

export const MOCK_BULK_QUOTES: BulkQuoteRequest[] = [
  {
    id: 'rfq_vm_501',
    rfqNumber: 'RFQ-2026-501',
    buyerId: MOCK_BUYER.id,
    buyerName: MOCK_BUYER.name,
    businessName: MOCK_BUYER.businessName,
    buyerLocation: 'Pune Bhosari MIDC Warehouse',
    produceName: 'Grade A Red Onion (Lasalgaon/Nashik)',
    category: 'vegetables',
    variety: 'Garwa Red',
    gradeRequired: 'A',
    targetQuantityKg: 5000,
    targetPricePerKg: 20.0,
    deliveryWarehouse: 'Pune Central Cold Hub (Bhosari)',
    targetDeliveryDate: '2026-08-18',
    specialRequirements: 'Must be packed in 50kg red ventilated mesh bags. Moisture below 12%.',
    status: 'responded',
    createdAt: '2026-08-12T11:00:00Z',
    responses: [
      {
        id: 'resp_ramesh_501',
        farmerId: MOCK_FARMER.id,
        farmerName: 'Ramesh Patil (Patil Agro)',
        farmerLocation: 'Niphad, Nashik (28 km)',
        offeredPricePerKg: 20.5,
        offeredQuantityKg: 5000,
        availableFromDate: '2026-08-17',
        notes: 'Can fulfill full 5,000 kg in 50kg fresh mesh bags. Guaranteed 55mm+ diameter.',
        status: 'offered',
        createdAt: '2026-08-12T15:30:00Z',
      },
      {
        id: 'resp_shinde_501',
        farmerId: MOCK_FARMER_SHINDE.id,
        farmerName: 'Anand Shinde',
        farmerLocation: 'Pimpalgaon, Nashik (42 km)',
        offeredPricePerKg: 21.0,
        offeredQuantityKg: 3500,
        availableFromDate: '2026-08-16',
        notes: 'Ready stock in Pimpalgaon warehouse.',
        status: 'offered',
        createdAt: '2026-08-12T16:45:00Z',
      },
    ],
  },
  {
    id: 'rfq_vm_502',
    rfqNumber: 'RFQ-2026-502',
    buyerId: MOCK_BUYER.id,
    buyerName: MOCK_BUYER.name,
    businessName: MOCK_BUYER.businessName,
    buyerLocation: 'Navi Mumbai Vashi Terminal',
    produceName: 'GI Sangli Rajapuri Turmeric Fingers',
    category: 'spices',
    gradeRequired: 'Premium',
    targetQuantityKg: 2000,
    targetPricePerKg: 138.0,
    deliveryWarehouse: 'Navi Mumbai APMC Terminal',
    targetDeliveryDate: '2026-08-25',
    specialRequirements: 'Curcumin lab test report required prior to dispatch.',
    status: 'pending',
    createdAt: '2026-08-13T05:00:00Z',
    responses: [],
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    targetRole: 'farmer',
    type: 'order',
    title: 'New Bulk Order Received (#VM-2026-98240)',
    body: 'Apex Fresh Agro Retail placed an order for 500 kg Hybrid Tomato (₹14,000). Please review and accept.',
    timestamp: '25 min ago',
    read: false,
    actionRoute: '/(farmer)/orders/ord_vm_98240',
  },
  {
    id: 'notif_2',
    targetRole: 'farmer',
    type: 'quote',
    title: 'New Bulk RFQ Inquiry Available',
    body: 'MahaFresh Wholesale requested quote for 5,000 kg Grade A Red Onion in Pune.',
    timestamp: '2 hours ago',
    read: false,
    actionRoute: '/(farmer)/orders',
  },
  {
    id: 'notif_3',
    targetRole: 'farmer',
    type: 'payment',
    title: 'Escrow Payout Settled: ₹27,300',
    body: 'Payment for order #VM-2026-98190 has been credited to your SBI Account (•••• 8842).',
    timestamp: 'Yesterday',
    read: true,
    actionRoute: '/(farmer)/earnings',
  },
  {
    id: 'notif_4',
    targetRole: 'buyer',
    type: 'quote',
    title: 'Farmer Responded to RFQ-2026-501',
    body: 'Ramesh Patil submitted an offer of ₹20.50/kg for your 5,000 kg Onion inquiry.',
    timestamp: '1 hour ago',
    read: false,
    actionRoute: '/(buyer)/quotes',
  },
  {
    id: 'notif_5',
    targetRole: 'buyer',
    type: 'delivery',
    title: 'Order Dispatched: VM-2026-98214',
    body: '800 kg Hybrid Tomato is being loaded on truck MH-15-EG-4910 from Lasalgaon Hub.',
    timestamp: '3 hours ago',
    read: false,
    actionRoute: '/(buyer)/orders/ord_vm_98214',
  },
];

export const MOCK_MANDI_RATES: MandiRateTickerItem[] = [
  {
    id: 'rate_1',
    commodity: 'Tomato (Hybrid)',
    mandi: 'Nashik APMC',
    state: 'MH',
    modalPrice: 2800,
    priceChange: 4.2,
    trend: 'up',
    arrivalTonnes: 420,
  },
  {
    id: 'rate_2',
    commodity: 'Red Onion (Garwa)',
    mandi: 'Lasalgaon Mandi',
    state: 'MH',
    modalPrice: 2150,
    priceChange: -1.8,
    trend: 'down',
    arrivalTonnes: 1250,
  },
  {
    id: 'rate_3',
    commodity: 'Turmeric (Rajapuri)',
    mandi: 'Sangli APMC',
    state: 'MH',
    modalPrice: 14200,
    priceChange: 2.1,
    trend: 'up',
    arrivalTonnes: 180,
  },
  {
    id: 'rate_4',
    commodity: 'Wheat (Sharbati)',
    mandi: 'Ahmednagar',
    state: 'MH',
    modalPrice: 3450,
    priceChange: 0.5,
    trend: 'stable',
    arrivalTonnes: 640,
  },
  {
    id: 'rate_5',
    commodity: 'Pomegranate (Bhagwa)',
    mandi: 'Solapur APMC',
    state: 'MH',
    modalPrice: 11000,
    priceChange: 3.4,
    trend: 'up',
    arrivalTonnes: 95,
  },
];

export const MOCK_EARNINGS_STATS = {
  totalRevenue: 348500,
  thisMonthRevenue: 78200,
  pendingEscrow: 36400,
  completedOrdersCount: 94,
  monthlyBreakdown: [
    { month: 'Mar', amount: 32000 },
    { month: 'Apr', amount: 48000 },
    { month: 'May', amount: 62000 },
    { month: 'Jun', amount: 55000 },
    { month: 'Jul', amount: 73300 },
    { month: 'Aug', amount: 78200 },
  ],
  transactions: [
    {
      id: 'tx_98190',
      orderNumber: 'VM-2026-98190',
      buyer: 'MahaFresh Wholesale Ltd',
      produce: 'Lasalgaon Red Onion (1,300 kg)',
      amount: 27300,
      status: 'settled',
      date: '12 Aug 2026',
      payoutRef: 'UTR-SBIN89123891',
    },
    {
      id: 'tx_97904',
      orderNumber: 'VM-2026-97904',
      buyer: 'Surat Agri Traders',
      produce: 'Premium Tomato (2,000 kg)',
      amount: 54000,
      status: 'settled',
      date: '04 Aug 2026',
      payoutRef: 'UTR-HDFC0019482',
    },
    {
      id: 'tx_97621',
      orderNumber: 'VM-2026-97621',
      buyer: 'Haldiram Snacks Procurement',
      produce: 'Chipsona Potato (4,500 kg)',
      amount: 76500,
      status: 'settled',
      date: '27 Jul 2026',
      payoutRef: 'UTR-ICIC7781294',
    },
    {
      id: 'tx_98214_pending',
      orderNumber: 'VM-2026-98214',
      buyer: 'MahaFresh Wholesale Ltd',
      produce: 'Premium Tomato (800 kg)',
      amount: 22400,
      status: 'in_escrow',
      date: '13 Aug 2026 (Pending Dispatch)',
      payoutRef: 'ONDC-ESC-98214',
    },
  ],
};
